In [1]:
import numpy as np
arr=np.array([[78,85,90],
             [45,60,55],
             [88,92,95],
             [30,40,35],
             [65,70,75]])
print(arr)
#metadata discovery
print(arr.shape)
print(type(arr))
#find the total number of element
print(arr.size)
print(arr[1])
print(arr[:,2])
#find specific marks for student 1 in subject 2

print(arr[0,1])


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
(5, 3)
<class 'numpy.ndarray'>
15
[45 60 55]
[90 55 95 35 75]
85


calculate the avg marks for each student
calculate the avg marks for subject

## filtering top performers
identify and display students whose avg marks are>=80

## global adjustment
add 5 grace marks to evry student for evr subject update the array using broadcasting

In [10]:
print(np.sum(arr,axis=1))

[253 160 275 105 210]


create a status matrix where

1.marks>=50 -1(pass)
2.marks<50 -0 (fail)
 to stanadardize failing grades replace all the marks below 40 with avalue of 40

In [7]:
result = np.where(arr>= 50, 1,0)
print(result)


[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


avg>=85 :grade a(score 10)
avg>=75 :grade b (score 8)
avg>=50 :grade c(score 6)
below 50 :no grade (score 0)
#use nested conditional logic within numpy


In [8]:
avg=arr.mean(axis=1)
score=np.where(avg>=85,10,
               np.where(avg>=75,8,
                        np.where(avg>=50,6,0)))
print("avg:" , avg)
print("score", score)

avg: [84.33333333 53.33333333 91.66666667 35.         70.        ]
score [ 8  6 10  0  6]


1. create a backup of the marks array
2. modify the original array(eg, set marks[0,0]=0)
3. check if the backup array changed or remained original
#marks.copy()

In [9]:
#backup
backup = arr.copy()
arr[0,0]=0
print("backup",backup)
print("original",arr)

backup [[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
original [[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


### use of copy function--- make change only in original array backup array remains the same no effect on backup array
