Case Study Scenario

Question 1: you are managing the electronic section of a store. you need to track the sales of 3 products: headphones
smartwatches and speakers over 4 days(monday to tuesday).
row 0: headphones
row 1: smartphones
row 2: speakers

In [ ]:
create 1d numpy array called cost price containing the prices for 3 items[1500,3000,5000]
create 2d numpy array called daily sales 
print the shape and dimension of both array

In [3]:
import numpy as np
cost_price=np.array([1500,3000,5000])
arr=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(arr.shape)
print(arr.ndim)
print(cost_price.shape)

(3, 4)
2
(3,)


add 2 bonus to every product 
calculate the total revenue for each day
use np.sqrt() 

In [ ]:
arr=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(arr+2)

print(np.dot(cost_price,arr))




[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]
[40000 58500 34000 56000]
