#### Level 2 — Operations & Reshaping (11–20)

1. Create a 1D array of size 9 and reshape it into 3×3.
2. Add 5 to every element of:
* a = np.array([2,4,6])
3. Multiply two arrays:
* a = np.array([1,2,3])
* b = np.array([4,5,6])
4. Find mean, max, and min of:
* a = np.array([5,10,15,20])
5. Transpose:
* a = np.array([5,10,15,20])




In [ ]:
import numpy as np


arr = np.array([1,2,3,4,5,6,7,8,9])
arr = arr.reshape((3,3))
print(arr)


a1 = np.array([2,4,6])
print(a1+5)

a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))
print(a*b)

a2 = np.array([5,10,15,20])
m1=np.mean(a2)
m2=np.max(a2)
m3=np.min(a2)
print(m1,m2,m3)

mat = np.array([[1,2],[3,4]])
t=mat.T
print(t)

a2 = np.array([5,12,8,20])
a2[a2 > 10]=10
print(a2)

a3 = np.array([10,60,45,80,30])
idx = np.where(a3 > 50)
print(idx)

r = np.random.rand(4,4)
print(r)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 7  9 11]
32
[ 4 10 18]
12.5 20 5
[[1 3]
 [2 4]]
[ 5 10  8 10]
(array([1, 3]),)
[[0.33488304 0.54051892 0.77990451 0.3836449 ]
 [0.51785112 0.77648428 0.13805085 0.65224869]
 [0.67457471 0.40995761 0.92228352 0.65419008]
 [0.18235541 0.93062603 0.34378015 0.48375279]]
