In [3]:
print("hello")
import numpy as np
arr=np.array([2,3,4,5,6,7,8,9])
print(arr)

hello
[2 3 4 5 6 7 8 9]


In [3]:
arr=np.array([2,3,4,5,6,7,8,9])
print(arr)

[2 3 4 5 6 7 8 9]


In [4]:
# create a list
lst=[1,'a',3,4,5]

# Convert list to NumPy array
arr=np.array(lst)

print(arr)
print(lst)

print(type(lst))
print(type(arr))

['1' 'a' '3' '4' '5']
[1, 'a', 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>


In [5]:
lst=[1,2,3,4,5]
lst=np.array(lst)
print(lst)
print(type(lst))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
array=np.array([1,2,3,4,5])
print("dimension", array.ndim)
print("no of element:", array.size)
print("data type",array.dtype)

# string datatype

# lst=["apple", "mango"]
# arr=np.array(lst)
arr=np.array(["isha","anisha"])
print("dimension", arr.ndim)
print("no of element:", arr.size)
print("data type",arr.dtype)


dimension 1
no of element: 5
data type int64
dimension 1
no of element: 2
data type <U6


In [10]:
arr=np.arange(5,50,22)
# 5 is step size
mul=np.arange(5,51,5)
#10 multiple of 2
n=np.arange(10,101,10)
print(n)
m=np.arange(2,21,2)
print(arr)
print(m)

[ 10  20  30  40  50  60  70  80  90 100]
[ 5 27 49]
[ 2  4  6  8 10 12 14 16 18 20]


In [14]:
#linspace is used to generate evenly spaced numbers between two values.
np.linspace(0,10,5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
#2D ARRAY

arr=np.array([[1,2],
              [3,4]])
a1=np.array([[],[]])
print(arr)
print(arr.size)
print(type(arr))
print(arr.ndim)
print(a1.ndim) 

[[1 2]
 [3 4]]
4
<class 'numpy.ndarray'>
2
2


In [26]:
a=np.ones(10)
b=np.ones((2,3))
c=np.identity(4)
d=np.full((2,2),10)
e=np.linspace(1,5)
print(a,b,c,d,e)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [[1. 1. 1.]
 [1. 1. 1.]] [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] [[10 10]
 [10 10]] [1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [ ]:
#axis=0 column 


Random Module

In [51]:
arr = np.random.randint(1, 101, 10)
r=np.random.rand(3,3)
#for getting in integer
r1=np.random.randint(1,100,10)
r2=np.random.rand(5)
print(r)
print(r1)
print(r2)
print(arr)



[[0.25182453 0.64037088 0.97111099]
 [0.63226283 0.41221257 0.98742513]
 [0.27102952 0.7593748  0.43642106]]
[26 11 88 24 19  1 58 56 73 20]
[0.90178776 0.23018481 0.7622592  0.79505282 0.08578173]
[32 86 52 45  6 88 50 58 47 75]


Reshaping array

In [52]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
a=np.zeros(5)
b=np.ones(3)
#creating matxics
c=np.zeros((3,3)) 
d=np.ones((2,3))
print(d)
print(a)
print(b)
print(c)
print(arr)
print(type)


[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0.]
[1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3]
 [4 5 6]]
<class 'type'>


Type conversion

In [16]:
arr=np.array([1.2,2.5,3.7])
arr1= arr.astype(int)
print(arr1)

[1 2 3]


Indexing and slicing


In [20]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[3])
print(arr[1:3])
print(arr[:2])
print(arr[::2])
print(arr[:-1])
print(arr[1:-1])


10
40
[20 30]
[10 20]
[10 30]
[10 20 30]
[20 30]


2D array

In [31]:
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
#row * col
print(mat[0,1])
print(mat[1])
#All rows except the last
print(mat[:-1])
#Fetching COLUMNS
mat[:, 1]
a=mat[:, 0:2]
print(a)

print(type(mat))
print(mat.shape)


2
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
<class 'numpy.ndarray'>
(3, 3)


In [24]:
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a,b)

[1 2 3] [99  2  3]


Arithmetic operation on numpy array

In [37]:
a=np.array([[1,2,3]])
b=np.array([4,5,6])
print(a*b)
print(a+10)

[[ 4 10 18]]
[[11 12 13]]


In [38]:
arr=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
30
5.678908345800274


Boolean indexing

In [41]:
arr=np.array([10,20,30,50])
print(arr[arr>25])
print(arr>25)

[30 50]
[False False  True  True]


Broadcasting Rule

In [42]:
arr=np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [43]:
arr=np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

#transpose

[[19 22]
 [43 50]]
